### ISSUE TITLE
What Terminal are you using?

### ISSUE THREAD

**Issue by sheharyarn** [andywer/leakage#13]
I just have to know, what terminal app is this screenshot from? Is this even a terminal - or just some text editor?

![](https://github.com/andywer/leakage/raw/master/docs/failing-test.png?raw=true)

**Comment by andywer** [comment]
Lol. You are already the 2nd one to ask.

It's the hyper terminal with the [hyper-snazzy](https://github.com/sindresorhus/hyper-snazzy) theme 😉

Maybe we should add a FAQ section... ^^

**Comment by sheharyarn** [comment]
Awesome! Thanks! :smile:
