### ISSUE TITLE
To Do: Add to node-memory-leak-tutorial

### ISSUE THREAD

**Issue by andywer** [andywer/leakage#21]
Once #7 is finished it might be a good idea to propose adding `leakage` to https://github.com/felixge/node-memory-leak-tutorial.

**Comment by DDeme** [comment]
I like this library but it take time to understand to write test cases  Examples and tutorials will be very helpful

**Comment by andywer** [comment]
@DDeme Good point. If you have any suggestions how to approach this, feel free to share or open a PR 🙂

**Comment by andywer** [comment]
Closing, since it's been open for ages and has little priority right now.
