### ISSUE TITLE
Node version support

### ISSUE THREAD

**Issue by btmills** [andywer/leakage#3]
Again, thank you for building this! It's much easier than trying to implement a leak test for one of my modules on my own.

What versions of Node.js do you intend to support? I'm testing on versions 4 and up, but destructuring is only supporting starting in v6, so prior versions currently encounter a syntax error at [iterations.js line 2](https://github.com/andywer/leakage/blob/4c38897b7e2b2715ff9abd5b99a81f611296a759/lib/iteration.js#L2). Would you be willing to accept a PR that makes this work on v4?

**Comment by andywer** [comment]
I tested it with node 6. But yeah, node 4+ should be the way to go :)

Would be covered by the follow-up PR to #1 I mentioned there in the review.
