### ISSUE TITLE
Failed to install on Windows

### ISSUE THREAD

**Issue by momocow** [andywer/leakage#33]
I am trying to installing the package on Win10 and it does not have `sys/time.h` for `@airbnb\node-memwatch` to be built.

```
d:\<...>\node_modules\@airbnb\node-memwatch\src\memwatch.cc(19): fatal error C1083: 無法開啟包含檔案: 'sys/time.h': No such file or directory [D:\<...>\node_modules\@airbnb\node-memwatch\bui
ld\memwatch.vcxproj]
```

Any alternatives or solution I can try for this?
Throw Windows away and embrace Ubuntu? 😂 (OMG

Thanks for the nice project anyway!

**Comment by andywer** [comment]
Hey @momocow!

> Any alternatives or solution I can try for this?
> Throw Windows away and embrace Ubuntu? 😂

Yeah, unfortunately that sounds like the best way to go... 😅

If that is not an option, try to re-post the issue at <https://github.com/airbnb/node-memwatch>.
Would be great if you'd share the solution here, though, in case they can help 🙂

**Comment by momocow** [comment]
@andywer I've tried using docker `node:8` image and it works. 😂 

Sadly, I found [airbnb/node-memwatch](https://github.com/airbnb/node-memwatch) no issues tab to file an issue.
Not sure if its upstream, [marcominetti/node-memwatch](https://github.com/marcominetti/node-memwatch), has the same issue in Windows.
Maybe I'll have a try.

**Comment by momocow** [comment]
I'm afraid that the compatibility problem for Windows is introduced in [airbnb's fork](https://github.com/airbnb/node-memwatch).

See [this git diff between airbnb's and marcominetti's fork](https://github.com/marcominetti/node-memwatch/compare/master...airbnb:master#diff-69f2d078b3741241d21a4c6dc64b61cfR19), which I have no where to post the issue. 😂

**Comment by andywer** [comment]
Ohh noooo... 🙈

So the solution is to use docker to run a real operating system?

**Comment by momocow** [comment]
Sad news for Windows users, but hopefully we still have Docker! 🐋 

> So the solution is to use docker to run a real operating system?

Yes, the easiest way is with the help of Docker, since it  requires `sys/time.h` in its build.
I have no knowledge how to ship it or make it available on Windows.

Maybe this issue worth you to mention about it in README for those Windows users?
(Surprisingly there's not even a Windows user file an issue here, except me. lol)
